name: GitHub Java  app
on:
  push:
    branches:
      - main
  pull_request:     
    types:           
      - opened
      - synchronize  
  workflow_dispatch:

jobs:
  my_first_job:

    runs-on: ubuntu-latest

    steps:
    
      - name: Set up JDK 17    
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'zulu'
          
      - name: Show Java version
        run: "java -version"
        
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: main

      - name: Show directory
        run: 'pwd'  

      - name: List files
        run: 'dir' 
        
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Clone another repository
      #   run: git clone https://github.com/DevOps2-Fundamentals/java-app-dimonkoval.git

      - name: Install dependecies
        run: 'mvn compile'

      - name: Build app
        run: 'mvn package -DskipTests'

      - name: Test app
        run: 'mvn test'

      # - name: Commit changes
      #   run: |
      #      git config --local user.name "GitHub Actions"
      #      git config --local user.email "actions@github.com"
      #      git add .
      #      git commit -m "Automated update"
      #      git push origin main
      # check commit
 
       
     
